### ISSUE TITLE
Seed fungerar ej korrekt

### ISSUE THREAD

**Issue by ehamrin** [mi222ep/1DV450_mi222ep#2]
Får detta felmeddelande när jag kör `rake db:seed`

```
NameError: uninitialized constant User::Application
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:133:in `compute_type'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.1.8/lib/active_record/reflection.rb:221:in `klass'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.1.8/lib/active_record/associations/association.rb:118:in `klass'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:36:in `reader'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.1.8/lib/active_record/associations/builder/association.rb:110:in `applications'
/vagrant/posapp/db/seeds.rb:13:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.1.8/lib/rails/engine.rb:543:in `load_seed'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:200:in `load_seed'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:174:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
```

**Comment by mi222ep** [comment]
Samma som issue #7, att jag inte var noggrann när jag bytte namn på klassen.
